basdatwebsite/basdatApp/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login-page/$', login_page, name='login'),
    url(r'^login/$', login, name='login-data'),
    url(r'^register/$', register_page, name='register'),
    url(r'^register/submit/$', register_narasumber, name='register_narasumber'),
    url(r'^validate-username/$', check_username_view, name='validate-username'),
    url(r'^validate-npm/$', check_npm_view, name='validate-npm'),
    url(r'^validate-pwd/$', validate_pwd, name='validate-pwd'),
    url(r'^getunivids/', getUniversitas, name='getunivids'),
    url(r'^logout/$', logout, name='logout'),
    url(r'polling-create/$', polling_create, name="polling_create"),
    url(r'^polling-create-func/$',  polling_create_func, name="polling_create_func"),
    url(r'polling-berita-create/$', polling_berita_create, name="polling_berita_create"),
    url(r'polling-berita-create-func/$', polling_berita_create_func, name="polling_berita_create_func"),
    url(r'berita-create/$', berita_create, name="berita_create"),
    url(r'berita-create-func/$', berita_create_func, name="berita_create_func"),
    url(r'testDBConnect/$', testDBConnect, name="testDBConnect"),
    url(r'profile_html/$', profile, name="profile_html"),
    url(r'polling_list_html/$', polling_list_html, name="polling_list_html"),
    url(r'articles_list_html/$', articles_list_html, name="articles_list_html"),
]

basdatwebsite/basdatwebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basdatApp import urls as basdatApp

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(basdatApp, namespace='basdatApp'))
]

basdatwebsite/basdatApp/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label="Username", max_length=50, required=True, widget=forms.TextInput(attrs={'class': 'mdl-textfield__input', 'type' :'text', 'id' : 'username', 'placeholder': 'Enter your username'}))
    password = forms.CharField(label="Password", max_length=50, required=True, widget=forms.TextInput(attrs={'class': 'mdl-textfield__input', 'type' :'password', 'id' : 'password', 'placeholder': 'Enter your password'}))

class RegisterForm(forms.Form):
    username = {
        'type': 'text',
        'class': 'mdl-textfield__input',
        'placeholder': 'Enter your username',
    }
    password = {
        'type': 'password',
        'class': 'mdl-textfield__input',
        'placeholder': 'Minimal 8 characters',
    }
    nama = {
        'type': 'text',
        'class': 'mdl-textfield__input',
        'placeholder': 'Enter your full name',
    }
    tempat_lahir = {
        'type': 'text',
        'class': 'mdl-textfield__input',
        'placeholder': 'Enter your birth place',
    }
    tanggal_lahir = {
        'type': 'date',
        'class': 'mdl-textfield__input',
        'placeholder': 'Enter your birth date',
    }
    email = {
        'type': 'email',
        'class': 'mdl-textfield__input',
        'placeholder': 'Enter your valid email adress',
    }
    no_hp = {
        'type': 'text',
        'class': 'mdl-textfield__input',
        'placeholder': '08xxxxxxxxxx',
    }
    role = {
        ('', '---------------'),
        ('dosen', 'Dosen'),
        ('staf', 'Staf'),
        ('mahasiswa', 'Mahasiswa'),
    }
    error_message = {
        'required': 'This field is required to fill',
    }
    nomor_identitas = {
        'type': 'text',
        'class': 'mdl-textfield__input',
        'placeholder': 'Enter your NIK/NPM',
    }
    jurusan = {
        'type': 'text',
        'class': 'mdl-textfield__input',
        'placeholder': 'Enter your major. Ex: Information System, etc.',
        'disabled':'true'
    }
    status = {
        ('', '---------------'),
        ('aktif', 'Aktif'),
        ('tidak', 'Tidak Aktif'),
    }
    posisi = {
        'type': 'text',
        'class': 'mdl-textfield__input',
        'placeholder': 'Enter your position. Ex: Analyst, etc.',
        'disabled':'true'
    }

    username = forms.CharField(label='Username', required=True, max_length=50, widget=forms.TextInput(attrs=username))
    password = forms.CharField(label='Password', required=True, max_length=50, widget=forms.TextInput(attrs=password))

    nama = forms.CharField(label='Nama Lengkap', required=True, max_length=50, widget=forms.TextInput(attrs=nama))
    email = forms.CharField(label='Email', required=True, max_length=50, widget=forms.TextInput(attrs=email))
    tempat = forms.CharField(label='Tempat Lahir', required=True, max_length=50, widget=forms.TextInput(attrs=tempat_lahir))
    tanggal = forms.DateTimeField(label='Tanggal Lahir', required=True, widget=forms.DateInput(attrs=tanggal_lahir))
    no_hp = forms.CharField(label='Nomor HP', max_length=50,required=False, widget=forms.TextInput(attrs=no_hp))
    nomor_identitas = forms.CharField(label='Nomor Identitas', required=True, max_length=20, widget=forms.TextInput(attrs=nomor_identitas))
    jurusan = forms.CharField(label='Jurusan', required=False, max_length=50, widget=forms.TextInput(attrs=jurusan))
    posisi = forms.CharField(label='Posisi', required=False, max_length=50, widget=forms.TextInput(attrs=posisi))

    role = forms.ChoiceField(label='Role', choices=role, required=True, widget=forms.Select(attrs={'class': 'mdl-textfield__input'}))
    status = forms.ChoiceField(label='Status Kemahasiswaan', required=False, choices=status, widget=forms.Select(attrs={'class': 'mdl-textfield__input','disabled':'true'}))

basdatwebsite/basdatApp/views.py
from django.shortcuts import render, redirect, reverse
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .database_things import *
from .forms import *
from datetime import date

response = {}

# Create your views here. Render stuff here too.
def index(request):
    return render(request, 'home/home.html', response)

def login_page(request):
    response['tes'] = "Tes"
    response['login_form'] = LoginForm
    print("masuk")
    return render(request, 'login/login.html', response)

def register_page(request):
    response['cek'] = "Halaman register"
    response['reg_form'] = RegisterForm
    form = RegisterForm
    print(form.errors)
    return render(request, 'login/regis.html', response)

def hasNumbers(inputString):
    return any(char.isdigit() for char in inputString)

@csrf_exempt
def validate_pwd(request):
    if request.method == "POST":
        password = request.POST.get('password', False)
        notif = ""
        list = []
        length = len(password)
        if (length<8):
            notif = "Password minimal harus 8 karakter"
            list.append(notif)
        if (hasNumbers(password)==False):
            notif = "Password harus mengandung angka"
            list.append(notif)
        print(list)
        data = {
            'list_of_notif' : list
        }
        return JsonResponse(data)

@csrf_exempt
def check_username_view(request):
    if request.method == 'POST':
        username = request.POST.get('username', False)
        data = check_username_json(username)
        return JsonResponse(data)

@csrf_exempt
def check_npm_view(request):
    if request.method == 'POST':
        nomor_identitas = request.POST.get('npm', False)
        role = request.POST.get('role', False)
        data = check_npm(role)
        return JsonResponse(data)

@csrf_exempt
def login(request):
    print("masuk form")
    form = LoginForm(data=request.POST)
    print(form.errors)
    
    if (request.method == 'POST' and form.is_valid()):
        username = request.POST.get('username', False)
        password = request.POST.get('password', False)
        exist = check_username(username)
        auth = user_auth(username, password)

        if not exist:
            messages.error(request, "Anda belum mendaftar")
            return HttpResponseRedirect(reverse('basdatApp:login'))
        
        elif auth:
            request.session['username'] = username
            request.session['is_login'] = "True"
            request.session['id'] = get_id[0]
            messages.success(request, "Anda berhasil login")
            return HttpResponseRedirect(reverse('basdatApp: index'))
        
        elif not auth:
            messages.error(request, "Username atau password salah")
            return HttpResponseRedirect(reverse('basdatApp:login'))

    else:
        return HttpResponse("null")

@csrf_exempt
def register_narasumber(request):
    print("masuk form")
    form = RegisterForm(data=request.POST)
    print("hai")
    print(request.method)
    print(form.is_valid())
    print(form.errors)
    
    if (request.method == 'POST' and form.is_valid()):
        id_narasumber = generate_id_narasumber()
        
        username = request.POST.get('username', False)
        password = request.POST.get('password', False)
        nama = request.POST.get('nama', False)
        role = request.POST.get('role', False)
        nomor_identitas = request.POST.get('nomor_identitas', False)
        email = request.POST.get('email', False)
        no_hp = request.POST.get('no_hp', False)
        tempat = request.POST.get('tempat', False)
        tanggal = request.POST.get('tanggal', False)
        status = request.POST.get('status', False)
        jurusan = request.POST.get('jurusan', False)
        posisi = request.POST.get('posisi', False)
        
        print(status)
        id_universitas = request.POST.get('id_universitas', False)

        query_mhs_lg = "insert into bmnc.MAHASISWA (id_narasumber,npm,status) values ("+str(id_narasumber)+", "+"'"+str(nomor_identitas)+"'"+", "+"'"+str(status)+"')"
        query_dosen = "insert into bmnc.DOSEN (id_narasumber,nik_dosen,jurusan) values ("+str(id_narasumber)+", "+"'"+str(nomor_identitas)+"'"+", "+"'"+str(jurusan)+"')"
        query_staf = "insert into bmnc.STAF (id_narasumber,nik_staf,posisi) values ("+str(id_narasumber)+", "+"'"+str(nomor_identitas)+"'"+", "+"'"+str(posisi)+"')"
        print(query_mhs_lg)
        print(query_dosen)
        print(query_staf)

        if role in ('dosen','staf','mahasiswa'):
            print(id_universitas)
            query = "insert into bmnc.NARASUMBER (id, nama, email, tempat, tanggal, no_hp, id_universitas, username, password) values ("+str(id_narasumber)+", "+"'"+str(nama)+"'"+", "+"'"+str(email)+"'"+", "+"'"+str(tempat)+"'"+", "+"'"+str(tanggal)+"'"+", "+"'"+str(no_hp)+"'"+", "+str(id_universitas)+", "+"'"+str(username)+"'"+", "+"'"+str(password)+"')"
            print(query)
            cursor.execute(query)

        # Insert operation mulai
        cursor = connection.cursor()
        if role == 'mahasiswa':
            cursor.execute(query_mhs_lg)
        elif role == 'dosen':
            cursor.execute(query_dosen)
        elif role == 'staf':
            cursor.execute(query_staf)
        cursor.close()
        # Insert op selesai

        messages.success(request, "Selamat! Anda berhasil mendaftar! Silakan login kembali untuk melanjutkan")
        return HttpResponseRedirect(reverse('basdatApp:login'))
    else:
        return HttpResponse("null")

def getUniversitas(request):
    if request.method == 'GET':
        return JsonResponse(get_id_universitas(), safe=False)

def logout(request):
    request.session['login'] = False
    try:
        request.session.flush()
    except KeyError:
        pass
    messages.info(request, "Anda berhasil logout.")
    return HttpResponseRedirect(reverse('basdatApp:index'))

# KODE MULAI DARI SINI DIHAR, gua komen gini biar gak lupa, mohon maklum
def berita_create(request):
    response['warning'] = False
    return render(request, 'berita/berita_create.html', response)

def polling_berita_create(request):
    response['warning'] = False
    return render(request, 'polling/polling_berita_create.html', response)

def polling_create(request):
    response['warning'] = False
    return render(request, 'polling/polling_create.html', response)

# Test if the DB connect or not
def testDBConnect(request):
    print(test())
    print("PRINTED THE ENTIRE ID OF UNIVERSITAS")
    return redirect("basdatApp:index")

# response['warning'] adalah boolean untuk render warning atau tidak
# response['warning_message'] untuk pesan dari warning
# TODO make auth here
def berita_create_func(request):
    # if request.session.get('login') == 'True':
    #     ====di sini kode post di bawah====
    # else:
    #     return render(request, 'berita/berita_create.html', response)
    
    if request.method == "POST":
        url = request.POST.get("url")
        judul = request.POST.get("judul")
        topik = request.POST.get("topik")
        jumlahKata = request.POST.get("jumlahKata")
        tag = reques.POST.get("tag")
        todayDate = date.today().isoformat()
        id_universitas_user = get_user_universitas(request.session.get("username"))
        
        insert_berita(url, judul, topik, todayDate, jumlahKata, id_universitas_user)
        
        return redirect("basdatApp:berita_create")

        
        
# response['warning'] adalah boolean untuk render warning atau tidak
# response['warning_message'] untuk pesan dari warning
# TODO make auth here
def polling_create_func(request):
    # if request.session.get('login') == 'True':
    #     ====di sini kode post di bawah====
    # else:
    #     return render(request, 'polling/polling_create.html', response)

    if request.method == "POST":
        id = generate_id_polling()
        url_mock = "iniUrlMock"
        deskripsi = request.POST.get("deskripsi")
        waktuMulai = request.POST.get("waktuMulai")
        waktuSelesai = request.POST.get("waktuSelesai")

        print(waktuSelesai)
        
        # insert for polling here
        insert_polling_biasa(id, waktumulai, waktuSelesai, url_mock, deskripsi)

        for key, value in request.POST.items():
            if key[:10] == "pertanyaan":
                insert_jawaban(id, value)
    return render(request, 'polling/polling_create.html', response)

# response['warning'] adalah boolean untuk render warning atau tidak
# response['warning_message'] untuk pesan dari warning
# TODO make auth here
def polling_berita_create_func(request):
    # if request.session.get('login') == 'True':
    #     ====di sini kode post di bawah====
    # else:
    #     return render(request, 'polling/polling_berita_create.html', response)
        
    if request.method == "POST":
        id = generate_id_polling()
        url = request.POST.get("url")
        waktuMulai = request.POST.get("waktuMulai")
        waktuSelesai = request.POST.get("waktuSelesai")

        print(waktuMulai)
        if url:
            if not berita_url_exist(url):
                response['warning'] = True
                response['warning_message'] = "URL doesn't exist!"
                return render(request, 'polling/polling_berita_create.html', response)

        # insert_polling_berita(id, waktuMulai, waktuSelesai, url)

        for key, value in request.POST.items():
            if key[:10] == "pertanyaan":
                insert_jawaban(id, value)
        return render(request, 'polling/polling_berita_create.html', response)

# END KODE BUATAN DIHAR

# TODO benerin ini, cursornya salah
# Benerin ini "jumlah" kayaknya gak guna deh
def profile(request):
    cursor = connection.cursor()
    cursor.execute('select count(*) from narasumber')
    jumlah = cursor.fetchone()[0]
    if jumlah != 0:

basdatwebsite/basdatApp/templates/polling/polling_berita_create.html
{% extends 'base.html' %} 
{% load static %}
{% block real_content %}
<!-- CONTEK INI UNTUK POLLING BERITA JUGA -->
<div class="mdl-grid mdl-grid--no-spacing">
    <div class="mdl-layout-spacer"></div>
    <div class="mdl-cell mdl-cell--6-col mdl-shadow--6dp" id="secondary-background">
        <div class="mdl-grid">
            <div class="mdl-layout-spacer"></div>
            <div class="create-berita-card mdl-card mdl-shadow--16dp mdl-cell--middle" id="main-card">
                <div class="mdl-card__title">
                    <h2 class="mdl-card__title-text">Polling Berita</h2>
                </div>
                <div class="mdl-card__supporting-text">
                    <!-- Form starts here, Im not going to add form until TK5 -->
                    <form id="main-form" action="{% url 'basdatApp:polling_berita_create_func' %}" method="POST">
                        {% csrf_token %}
                        <div id="field-form">
                            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-textfield--full-width">
                                <input class="mdl-textfield__input" type="text" id="url" name="url">
                                <label class="mdl-textfield__label">URL</label>
                            </div>
                            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-textfield--full-width">
                                <input name="waktuMulai" id="waktuMulai" class="mdl-textfield__input" type="date">
                                <label class="mdl-textfield__label">Waktu Mulai</label>
                            </div>
                            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-textfield--full-width">
                                <input name="waktuSelesai" id="waktuSelesai" class="mdl-textfield__input" type="date">
                                <label class="mdl-textfield__label">Waktu Selesai</label>
                            </div>
                            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-textfield--full-width">
                                <input class="mdl-textfield__input" type="text" id="pertanyaan0" name="pertanyaan0">
                                <label class="mdl-textfield__label">Pertanyaan Seputar Polling</label>
                            </div>
                        </div>
                        <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" id="add-pertanyaan">
                            Tambah Pertanyaan
                        </a>
                        <div class="mdl-card__actions mdl-card--border">
                            <input class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" type="submit" name="submit" value="Submit">
                        </div>
                    </form>
                    <!-- Form ends here -->
                </div>
                 {% if warning %}
                <div class="mdl-card__menu">
                    <span class="mdl-chip">
                        <span class="mdl-chip__text">{{ warning_message }}</span>
                    </span>
                </div>
                {% endif %}
            </div>
            <div class="mdl-layout-spacer"></div>
        </div>
    </div>
    <div class="mdl-layout-spacer"></div>
</div>
{% endblock %} 

{% block styles %}
<style>
    .create-berita-card>.mdl-card__title {
        color: #fff;
        height: 150px;
        background: url("{% static 'images/pjk9gxle.jpg' %}") center / cover;
    }

    .create-berita-card.mdl-card {
        width: 512px;
    }

    #secondary-background {
        background-color: #bbdefb;
        height: 100vh;
    }

    #main-card {
        top: 10vh;
    }
    
    .mdl-chip {
        background-color: #E30425;
        color: white;
    }
</style>
{% endblock %} 

{% block real_scripts %}
<script>
    (function () {
            'use strict';
            window['counter'] = 0;
            var addPertanyaan = document.querySelector('#add-pertanyaan');
            addPertanyaan.addEventListener('click', function () {
                var namaField = "pertanyaan" + (++counter);
                $("#field-form").append('<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-textfield--full-width"><input class="mdl-textfield__input" type="text" id="' + namaField + '" name="' + namaField + '"></input><label class="mdl-textfield__label">Pertanyaan Seputar Polling</label></div>');
                $('#secondary-background').height(function (index, height) {
                    return (height + 42.88 + "px");
                });
                componentHandler.upgradeDom();
            });
        }());
</script>
{% endblock %}

basdatwebsite/basdatApp/templates/polling/polling_create.html
{% extends 'base.html' %} 
{% load static %}
{% block real_content %}
<!-- CONTEK INI UNTUK POLLING BERITA JUGA -->
<div class="mdl-grid mdl-grid--no-spacing">
    <div class="mdl-layout-spacer"></div>
    <div class="mdl-cell mdl-cell--6-col mdl-shadow--6dp" id="secondary-background">
        <div class="mdl-grid">
            <div class="mdl-layout-spacer"></div>
            <div class="create-berita-card mdl-card mdl-shadow--16dp mdl-cell--middle" id="main-card">
                <div class="mdl-card__title">
                    <h2 class="mdl-card__title-text">Polling</h2>
                </div>
                <div class="mdl-card__supporting-text">
                    <!-- Form starts here, Im not going to add form until TK5 -->
                    <form id="main-form" action="{% url 'basdatApp:polling_create_func' %}" method="POST">
                        {% csrf_token %}
                        <div id="field-form">
                            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-textfield--full-width">
                                <input class="mdl-textfield__input" type="text" id="deskripsi" name="deskripsi">
                                <label class="mdl-textfield__label">Deskripsi</label>
                            </div>
                            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-textfield--full-width">
                                <input name="waktuMulai" id="waktuMulai" class="mdl-textfield__input" type="date">
                                <label class="mdl-textfield__label">Waktu Mulai</label>
                            </div>
                            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-textfield--full-width">
                                <input name="waktuSelesai" id="waktuSelesai" class="mdl-textfield__input" type="date">
                                <label class="mdl-textfield__label">Waktu Selesai</label>
                            </div>
                            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-textfield--full-width">
                                <input class="mdl-textfield__input" type="text" id="pertanyaan0" name="pertanyaan0">
                                <label class="mdl-textfield__label">Pertanyaan Seputar Polling</label>
                            </div>
                        </div>
                        <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" id="add-pertanyaan">
                            Tambah Pertanyaan
                        </a>
                        <div class="mdl-card__actions mdl-card--border">
                            <input class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" type="submit" name="submit" value="Submit">
                        </div>
                    </form>
                    <!-- Form ends here -->
                </div>
                {% if warning %}
                <div class="mdl-card__menu">
                    <span class="mdl-chip">
                        <span class="mdl-chip__text">{{ warning_message }}</span>
                    </span>
                </div>
                {% endif %}
            </div>
            <div class="mdl-layout-spacer"></div>
        </div>
    </div>
    <div class="mdl-layout-spacer"></div>
</div>
{% endblock %} 

{% block styles %}
<style>
    .create-berita-card>.mdl-card__title {
        color: #fff;
        height: 150px;
        background: url("{% static 'images/pjk9gxle.jpg' %}") center / cover;
    }

    .create-berita-card.mdl-card {
        width: 512px;
    }

    #secondary-background {
        background-color: #bbdefb;
        height: 100vh;
    }

    #main-card {
        top: 10vh;
    }

    .mdl-chip {
        background-color: #E30425;
        color: white;
    }
</style>
{% endblock %} 

{% block real_scripts %}
<script>
    (function () {
            'use strict';
            window['counter'] = 0;
            var addPertanyaan = document.querySelector('#add-pertanyaan');
            addPertanyaan.addEventListener('click', function () {
                var namaField = "pertanyaan" + (++counter);
                $("#field-form").append('<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-textfield--full-width"><input class="mdl-textfield__input" type="text" id="' + namaField + '" name="' + namaField + '"></input><label class="mdl-textfield__label">Pertanyaan Seputar Polling</label></div>');
                $('#secondary-background').height(function (index, height) {
                    return (height + 42.88 + "px");
                });
                componentHandler.upgradeDom();
            });
        }());
</script>
{% endblock %}