basdatwebsite/basdatApp/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login-page/$', login_page, name='login'),
    url(r'^login/$', login, name='login-data'),
    url(r'^register/$', register_page, name='register'),
    url(r'^register/submit/$', register_narasumber, name='register_narasumber'),
    url(r'^validate-username/$', check_username_view, name='validate-username'),
    url(r'^validate-npm/$', check_npm_view, name='validate-npm'),
    url(r'^validate-pwd/$', validate_pwd, name='validate-pwd'),
    url(r'^getunivids/', getUniversitas, name='getunivids'),
    url(r'^logout/$', logout, name='logout'),
    url(r'polling-create/$', polling_create, name="polling_create"),
    url(r'^polling-create-func/$',  polling_create_func, name="polling_create_func"),
    url(r'polling-berita-create/$', polling_berita_create, name="polling_berita_create"),
    url(r'polling-berita-create-func/$', polling_berita_create_func, name="polling_berita_create_func"),
    url(r'berita-create/$', berita_create, name="berita_create"),
    url(r'berita-create-func/$', berita_create_func, name="berita_create_func"),
    url(r'testDBConnect/$', testDBConnect, name="testDBConnect"),
    url(r'profile_html/$', profile, name="profile_html"),
    url(r'polling_list_html/$', polling_list_html, name="polling_list_html"),
    url(r'articles_list_html/$', articles_list_html, name="articles_list_html"),
]

basdatwebsite/basdatwebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basdatApp import urls as basdatApp

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(basdatApp, namespace='basdatApp'))
]

basdatwebsite/templates/base.html
<!DOCTYPE html>
<html>
{% load static %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<link rel="stylesheet" href="{% static 'mdl/material.min.css' %}">
<script src="{% static 'mdl/material.min.js' %}"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<script src="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.min.js"></script>
{# Load the tag library #} {% load bootstrap3 %} {# Load CSS and JavaScript #} {% bootstrap_css %} {% bootstrap_javascript%} {# Display django.contrib.messages as Bootstrap alerts #} {% bootstrap_messages %}
<!-- Always shows a header, even in smaller screens. -->
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <!-- Title -->
      <span class="mdl-layout-title"> BMNC Corporation </span>
      <!-- Add spacer, to align navigation to the right -->
      <div class="mdl-layout-spacer"></div>
      <!-- Navigation. We hide it in small screens. -->
      <nav class="mdl-navigation mdl-layout--large-screen-only">
        <a class="mdl-navigation__link" href="{% url 'basdatApp:index' %}"> Home </a>
        <a class="mdl-navigation__link" href="{% url 'basdatApp:logout' %}"> Logout </a>
      </nav>
    </div>
  </header> 
  <div class="mdl-layout__drawer">
    <span class="mdl-layout-title">All Demos</span>
    <nav class="mdl-navigation">
      <!-- TODO Fill the href please. -->
      <a class="mdl-navigation__link" href="{% url 'basdatApp:login' %}"> Login </a>
      <a class="mdl-navigation__link" href="{% url 'basdatApp:register' %}">Register</a>
      <!-- Dihar -->
      <a class="mdl-navigation__link" href="{% url 'basdatApp:berita_create' %}"> Create Berita </a>
      <a class="mdl-navigation__link" href="{% url 'basdatApp:polling_berita_create' %}"> Create News Polling </a>
      <a class="mdl-navigation__link" href="{% url 'basdatApp:polling_create' %}"> Create Regular Polling </a>
      <!-- END Dihar -->
      <a class="mdl-navigation__link" href="{% url 'basdatApp:profile_html' %}"> Profil Pribadi </a>
      <a class="mdl-navigation__link" href="{% url 'basdatApp:polling_list_html' %}"> Polling List </a>
      <a class="mdl-navigation__link" href="{% url 'basdatApp:articles_list_html' %}"> Articles List </a>
    </nav>
  </div>

<main class="mdl-layout__content">
  {% block real_content %}{% endblock %}
</main>
</div> <!--this is the div for the header. A little bit of hack to do this thing properly.-->
{% block other_body %}{% endblock %}
{% block real_scripts %}{% endblock %}
{% block styles %} {% endblock %}
</html>